name: common pipeline workflow
on: 
  workflow_call:
    inputs:
      app_name:
        description: 'Application Name'
        required: true
        type: string
      proj:
        description: 'Project Name' 
        required: true
        type: string
      env:
        description: 'Dev EnvironmenT'
        required: true
        type: boolean
        default: false

jobs:
  setup_common_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: setup common pipeline
        run:  |
          echo "this is common pipeline for ${{ inputs.proj }} project"
          echo "application name is ${{ inputs.app_name }} microservices"
          echo "deployment environment is ${{ inputs.env }}"
        