name: github common workflows for NodeJS
on: 
  workflow_call:
    inputs:
      proj:
        description: project name
        type: string
        required: true
      env:
        description: target environment
        type: string
        required: true
      deployment:
        description: deployment using Github Actions
        type: string
        required: true
        default: github-actions

jobs:
  cmn-nodejs-feature-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: nodejsfeaturepipeline
        uses: actions/checkout@v6
      - name: listing files
        run: ls -l